lobbin:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/pruebadb?serverTimezone=America/Bogota&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
